name: Code checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check-code:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10']
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v2

      - name: Install Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Dependencies installation
        run: |
          python -m pip install -U pip
          python -m pip install -r requirements.txt
          python -m pip install flake8 mypy isort pytest

      - name: flake8
        run: flake8 .

      - name: isort
        run: isort --check-only .

      - name: mypy
        run: mypy .

      - name: pytest
        run: pytest .
